name: coffeeshop
description: Coffee Shop Order Management App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^4.10.0
  firebase_auth: ^6.5.2
  cloud_firestore: ^6.5.0
  firebase_storage: ^13.4.2

  # State Management
  flutter_riverpod: ^3.0.0
  riverpod_annotation: ^3.0.0

  # Navigation
  go_router: ^17.3.0

  # UI
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  fl_chart: ^1.2.0
  badges: ^3.1.2
  gap: ^3.0.1
  intl: ^0.20.2

  # Utils
  uuid: ^4.5.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  logger: ^2.4.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.4.12
  riverpod_generator: ^3.0.0
  freezed: ^3.0.0
  json_serializable: ^6.8.0
  riverpod_lint: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
